const GET_RECIPES_STARTED = "GET_RECIPES_STARTED";
const GET_RECIPES_SUCCESS = "GET_RECIPES_SUCCESS";
const GET_RECIPES_FAILED = "GET_RECIPES_FAILED";
const GET_RECIPES_NOTSTARTED = "GET_RECIPES_NOTSTARTED";

export {
  GET_RECIPES_STARTED,
  GET_RECIPES_SUCCESS,
  GET_RECIPES_FAILED,
  GET_RECIPES_NOTSTARTED,
};
